#ifndef CPPLIB_TESTING_CONFIG_HPP
#define CPPLIB_TESTING_CONFIG_HPP

#define TEST_ARR2D 0
#define TEST_CSTR 0
#define TEST_REGEXGLOB 0
#define TEST_LENGTHOF 0
#define TEST_ONSCOPEEXIT 0
#define TEST_PGM8 0
#define TEST_RLE 1
#define TEST_LOGGER 0

#endif // CPPLIB_TESTING_CONFIG_HPP
