#ifndef CPPLIB_TEST_CONFIG_HPP
#define CPPLIB_TEST_CONFIG_HPP

#define TEST_ARR2D 1
#define TEST_CSTR 1
#define TEST_REGEXGLOB 1
#define TEST_LENGTHOF 1
#define TEST_ONSCOPEEXIT 1
#define TEST_PGM8 1
#define TEST_LOGGER 1

#endif // CPPLIB_TEST_CONFIG_HPP
